# Generated by Django 2.2.12 on 2020-11-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vid_id', models.CharField(max_length=50)),
                ('thumbnail', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=500)),
            ],
        ),
    ]
