# Generated by Django 2.2.12 on 2020-11-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='user',
        ),
    ]
